[package]
name = "f1s-client"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_14"] }
f1s-lib = {git = "https://github.com/DreamsOneiro/f1s-lib"}
